### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by time007gc** [miku-gg/miku#1]
Task list:

- [] Add temperature, frequency/presence penalty, and max tokens sliders
- [] Add regenerate button
- [] Move the bot response textbox lower
- [] Fix prompt to be more similar to rokos

**Comment by Yardanico** [comment]
Thanks for the project, the code and the architecture looks much cleaner than TavernAI! About the TTS and services - may I propose adding support for NovelAI? The good thing is that NovelAI has *both* text generation and TTS.
